"""Base strategy interface for all trading strategies."""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Optional
import pandas as pd


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    timestamp: str
    side: str  # "buy" or "sell"
    price: float
    reason: str = ""


@dataclass
class StrategyParam:
    """Describes a configurable parameter for a strategy."""
    name: str
    label: str
    type: str  # "int", "float", "select"
    default: any
    min: Optional[float] = None
    max: Optional[float] = None
    step: Optional[float] = None
    options: Optional[List[str]] = None


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    name: str = "Base Strategy"
    description: str = ""
    category: str = "general"

    @classmethod
    @abstractmethod
    def get_params(cls) -> List[StrategyParam]:
        """Return the list of configurable parameters."""
        ...

    @abstractmethod
    def generate_signals(self, df: pd.DataFrame, params: Dict) -> pd.DataFrame:
        """
        Given OHLCV data, add signal columns and return the augmented DataFrame.
        Must add a 'signal' column with values: 1 (buy), -1 (sell), 0 (hold).
        """
        ...

    @classmethod
    def info(cls) -> Dict:
        """Return strategy metadata."""
        return {
            "name": cls.name,
            "description": cls.description,
            "category": cls.category,
            "params": [
                {
                    "name": p.name, "label": p.label, "type": p.type,
                    "default": p.default, "min": p.min, "max": p.max,
                    "step": p.step, "options": p.options,
                }
                for p in cls.get_params()
            ],
        }
